services:
  - type: redis
    name: jack-automotive-redis
    plan: starter
    maxmemoryPolicy: allkeys-lru

  - type: web
    name: jack-automotive-ai-assistant
    env: node
    plan: starter
    buildCommand: NODE_ENV=development npm install && npm run build && npm run build:fallback
    startCommand: NODE_ENV=production npm run server
    envVars:
      - key: PORT
        value: 3001
      - key: NODE_ENV
        value: production
      - key: REDIS_HOST
        fromService:
          type: redis
          name: jack-automotive-redis
          property: host
      - key: REDIS_PORT
        fromService:
          type: redis
          name: jack-automotive-redis
          property: port
      - key: REDIS_PASSWORD
        fromService:
          type: redis
          name: jack-automotive-redis
          property: password
      - key: REDIS_DB
        value: 0
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: ELEVENLABS_API_KEY
        sync: false
      - key: ELEVENLABS_AGENT_ID
        sync: false
      - key: ELEVENLABS_PHONE_NUMBER_ID
        sync: false
      - key: TWILIO_ACCOUNT_SID
        sync: false
      - key: TWILIO_AUTH_TOKEN
        sync: false
      - key: TWILIO_PHONE_NUMBER
        sync: false
    healthCheckPath: /api/health 